/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import Controlador.CategoriaControlador;
import Modelo.Categoria;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author kreiv
 */
public class VistaCategorias extends javax.swing.JPanel {
    
    /**
     * Creates new form VistaCategorias
     */
    public VistaCategorias() {
       initComponents();
       this.categoriaControlador = new CategoriaControlador();
       cargarDatosTabla();
        
    }
    
    private void cargarDatosTabla(){
        CategoriaControlador controlador =new CategoriaControlador();
        List<Categoria> categorias = controlador.obtenerTodasCategorias();
        
        if (categorias != null){
            
            DefaultTableModel model = (DefaultTableModel) TablaCategorias.getModel();
            
            model.setRowCount(0);
            
            for (Categoria cat : categorias){
                Object[] row = {
                   cat.getIdCategoria(),
                    cat.getNombreCategoria(),
                    cat.getDescripcionCategoria()
                };
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextNombreCategoria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextDescripcionCategoria = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jTextBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCategorias = new javax.swing.JTable();

        setLayout(null);

        jLabel1.setText("Nombre Categoria");
        add(jLabel1);
        jLabel1.setBounds(15, 29, 110, 16);

        TextNombreCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreCategoriaActionPerformed(evt);
            }
        });
        add(TextNombreCategoria);
        TextNombreCategoria.setBounds(15, 51, 160, 22);

        jLabel2.setText("Descripcion Categoria");
        add(jLabel2);
        jLabel2.setBounds(199, 29, 116, 16);
        add(TextDescripcionCategoria);
        TextDescripcionCategoria.setBounds(199, 51, 160, 22);

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonGuardar(evt);
            }
        });
        add(jButtonGuardar);
        jButtonGuardar.setBounds(390, 50, 120, 23);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar);
        btnBuscar.setBounds(390, 150, 120, 23);

        btnEliminar.setText("Eliminar");
        add(btnEliminar);
        btnEliminar.setBounds(660, 150, 116, 23);

        btnEditar.setText("Editar");
        add(btnEditar);
        btnEditar.setBounds(530, 150, 116, 23);
        add(jTextBuscar);
        jTextBuscar.setBounds(16, 148, 340, 22);

        TablaCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Categoria", "Nombre", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaCategorias.setPreferredSize(new java.awt.Dimension(300, 230));
        jScrollPane1.setViewportView(TablaCategorias);
        TablaCategorias.getAccessibleContext().setAccessibleName("");

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 760, 180);
    }// </editor-fold>//GEN-END:initComponents

    private void TextNombreCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNombreCategoriaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void accionBotonGuardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonGuardar
        // TODO add your handling code here:
        String nombre = TextNombreCategoria.getText();
        String descripcion = TextDescripcionCategoria.getText();
        
        if (!nombre.isEmpty()&& !descripcion.isEmpty()){
           
            cargarDatosTabla();
            TextNombreCategoria.setText("");
            TextDescripcionCategoria.setText("");
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos.","Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accionBotonGuardar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCategorias;
    private javax.swing.JTextField TextDescripcionCategoria;
    private javax.swing.JTextField TextNombreCategoria;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextBuscar;
    // End of variables declaration//GEN-END:variables
}
