/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import Controlador.EmpleadoControlador;
import Modelo.Empleado;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import javax.swing.JTextField;
/**
 *
 * @author kreiv
 */
public class VistaEmpleados extends javax.swing.JPanel {
    private final EmpleadoControlador empleadoControlador;
    private Integer idEmpleadoSeleccionado = null;

    /**
     * Creates new form VistaEmpleados
     */
    public VistaEmpleados() {
        initComponents();
        this.empleadoControlador = new EmpleadoControlador();
        selectorfechaContratacion.setDate(new Date());
        ((JTextField) selectorfechaContratacion.getDateEditor().getUiComponent()).setEditable(false);
        cargarDatosTabla();
    }
      
private void cargarDatosTabla() {
List<Empleado> empleados = empleadoControlador.obtenerTodosEmpleados();
if (empleados != null) {
DefaultTableModel model = (DefaultTableModel) TablaEmpleados.getModel();
model.setRowCount(0);
for (Empleado emp : empleados) {
Object[] row = {
emp.getIdEmpleado(),
emp.getPrimerNombre(),
emp.getSegundoNombre(),
emp.getPrimerApellido(),
emp.getSegundoApellido(),
emp.getCelular(),
emp.getCargo(),
emp.getFechaContratacion()
};
model.addRow(row);
}
}
    }

private void limpiar() {
TextPrimerNombre.setText("");
TextSegundoNombre.setText("");
TextPrimerApellido.setText("");
TextSegundoApellido.setText("");
TextCelular.setText("");
TextBuscar.setText("");
idEmpleadoSeleccionado = null;
selectorfechaContratacion.setDate(new Date());
btnEliminar.setEnabled(true);
btnGuardar.setEnabled(true);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextPrimerNombre = new javax.swing.JTextField();
        TextSegundoNombre = new javax.swing.JTextField();
        TextPrimerApellido = new javax.swing.JTextField();
        TextSegundoApellido = new javax.swing.JTextField();
        TextCelular = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TextBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEmpleados = new javax.swing.JTable();
        selectorfechaContratacion = new com.toedter.calendar.JDateChooser();
        ComboCargo = new javax.swing.JComboBox<>();

        jLabel1.setText("Primer Nombre");

        jLabel2.setText("Segundo Nombre");

        jLabel3.setText("Primer Apellido");

        jLabel4.setText("Segundo Apellido");

        jLabel5.setText("Celular");

        jLabel6.setText("Cargar");

        jLabel7.setText("Fecha Contratación");

        jLabel8.setText("Buscar");

        TextBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textBuscarKeyTyped(evt);
            }
        });

        jButton1.setText("Limpiar");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonGuardar(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonEliminar(evt);
            }
        });

        jButton4.setText("Actualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonActualzar(evt);
            }
        });

        TablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Empleado", "Nombre 1", "Nombre 2", "Apellido 1", "Apellido 2", "Celular", "Cargar", "Fecha Contratación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaEmpleados);

        ComboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Cagero" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextPrimerNombre))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextSegundoNombre))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextPrimerApellido))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextSegundoApellido))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(TextCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ComboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(selectorfechaContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(selectorfechaContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accionBotonGuardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonGuardar
        // TODO add your handling code here:
        Date fecha = this.selectorfechaContratacion.getDate();
        java.util.Date fechaContratacion = new java.sql.Date(fecha.getTime());
        String PrimerNombre = TextPrimerNombre.getText();
        String SegundoNombre = TextSegundoNombre.getText();
        String PrimerApellido = TextPrimerApellido.getText();
        String SegundoApellido = TextSegundoApellido.getText();
        String Celular = TextCelular.getText();
        String Cargo = (String) ComboCargo.getSelectedItem();
        
        if (!PrimerNombre.isEmpty()&& !PrimerApellido.isEmpty()&& !Celular.isEmpty()&& !Cargo.isEmpty()){
            try{
                empleadoControlador.crearEmpleado(PrimerNombre, SegundoNombre, PrimerApellido, SegundoApellido, Celular, Cargo, fechaContratacion);
                limpiar();
            }catch (Exception e){
                javax.swing.JOptionPane.showMessageDialog(this,"Error:"+ e.getMessage(),"Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Llene los campos no sea imbécil.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accionBotonGuardar

    private void accionBotonEliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonEliminar
        // TODO add your handling code here:
        int filaSeleccionada = TablaEmpleados.getSelectedRow();
        if (filaSeleccionada != -1){
            int idEmpleado = (int) TablaEmpleados.getValueAt(filaSeleccionada, 0);
            empleadoControlador.eliminarEmpleado(idEmpleado);
            cargarDatosTabla();
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "seleccione una fila para eliminar.","Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accionBotonEliminar

    private void tablaEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEmpleadoMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2){
            int filaSeleccionada = TablaEmpleados.getSelectedRow();
            if (filaSeleccionada != -1){
                idEmpleadoSeleccionado = (int) TablaEmpleados.getValueAt(filaSeleccionada, 0);
                String PrimerNombre = (String) TablaEmpleados.getValueAt(filaSeleccionada, 1);
                String SegundoNombre = (String) TablaEmpleados.getValueAt(filaSeleccionada, 2);
                String PrimerApellido = (String) TablaEmpleados.getValueAt(filaSeleccionada, 3);
                String SegundoApellido = (String) TablaEmpleados.getValueAt(filaSeleccionada, 4);
                String Celular = (String) TablaEmpleados.getValueAt(filaSeleccionada, 5);
                String Cargo = (String) TablaEmpleados.getValueAt(filaSeleccionada, 6);
                Date fecha = (Date) TablaEmpleados.getValueAt(filaSeleccionada, 7);
                
                TextPrimerNombre.setText(PrimerNombre);
                TextSegundoNombre.setText(SegundoNombre != null ? SegundoNombre: "");
                TextPrimerApellido.setText(PrimerApellido);
                TextSegundoApellido.setText(SegundoApellido != null ? SegundoApellido: "");
                TextCelular.setText(Celular);
                ComboCargo.setSelectedItem(Cargo  != null ? Cargo: "Seleccionar");
                
                selectorfechaContratacion.setDate(fecha);
                
                btnEliminar.setEnabled(false);
                btnGuardar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tablaEmpleadoMouseClicked

    private void accionBotonActualzar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonActualzar
        // TODO add your handling code here:
        String PrimerNombre = TextPrimerNombre.getText();
        String SegundoNombre = TextSegundoNombre.getText();
        String PrimerApellido = TextPrimerApellido.getText();
        String SegundoApellido = TextSegundoApellido.getText();
        String Celular = TextCelular.getText();
        String Cargo = (String) ComboCargo.getSelectedItem();
        Date Fecha = this.selectorfechaContratacion.getDate();
        java.sql.Date fechaContratacion = new java.sql.Date(Fecha.getTime());
        
        if (idEmpleadoSeleccionado != null && !PrimerNombre.isEmpty()&& !PrimerApellido.isEmpty()&& !Celular.isEmpty()){
            try{
                empleadoControlador.actualizarEmpleado(idEmpleadoSeleccionado, PrimerNombre, SegundoNombre, PrimerApellido, SegundoApellido, Celular, Cargo, fechaContratacion);
                cargarDatosTabla();
            }catch(Exception e){
                javax.swing.JOptionPane.showMessageDialog(this, "Error:"+ e.getMessage(),"Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Llenar los campos no sea tan pendejo.","Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accionBotonActualzar

    private void textBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBuscarKeyTyped
        // TODO add your handling code here:
        String textoBusqueda = TextBuscar.getText().trim().toLowerCase();
        List<Empleado> empleados = empleadoControlador.obtenerTodosEmpleados();
        
        DefaultTableModel modelo =(DefaultTableModel)TablaEmpleados.getModel();
        modelo.setRowCount(0);
        
        if(empleados != null){
            for(Empleado emp : empleados){
                if(textoBusqueda.isEmpty()||
                        emp.getPrimerNombre().toLowerCase().contains(textoBusqueda)||
                        (emp.getSegundoNombre()!=null && emp.getSegundoNombre().toLowerCase().toLowerCase().contains(textoBusqueda))||
                        emp.getPrimerApellido().toLowerCase().contains(textoBusqueda)||
                        (emp.getSegundoApellido() !=null && emp.getSegundoApellido().toLowerCase().contains(textoBusqueda))||
                        emp.getCelular().toLowerCase().contains(textoBusqueda)||
                        emp.getCargo().toLowerCase().contains(textoBusqueda)){
                    Object[] fila = {
                      emp.getIdEmpleado(),
                      emp.getPrimerNombre(),
                      emp.getSegundoNombre(),
                      emp.getPrimerApellido(),
                      emp.getSegundoApellido(),
                      emp.getCelular(),
                      emp.getCargo(),
                      emp.getFechaContratacion()
                    };
                    modelo.addRow(fila);
                }
            }
        }
    }//GEN-LAST:event_textBuscarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCargo;
    private javax.swing.JTable TablaEmpleados;
    private javax.swing.JTextField TextBuscar;
    private javax.swing.JTextField TextCelular;
    private javax.swing.JTextField TextPrimerApellido;
    private javax.swing.JTextField TextPrimerNombre;
    private javax.swing.JTextField TextSegundoApellido;
    private javax.swing.JTextField TextSegundoNombre;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser selectorfechaContratacion;
    // End of variables declaration//GEN-END:variables
}
