/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import Controlador.ClienteControlador;
import Modelo.Cliente;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kreiv
 */
public class VistaClientes extends javax.swing.JPanel {
    private final ClienteControlador clienteControlador;
    private Integer idClienteSeleccionado = null;

    /**
     * Creates new form VistaClientes
     */
    public VistaClientes() {
        initComponents();
        this.clienteControlador = new ClienteControlador();
        cargarDatosTabla();
    }

    private void cargarDatosTabla(){
        List<Cliente> clientes = clienteControlador.obtenerTodosClientes();
        
        if(clientes != null){
            DefaultTableModel model = (DefaultTableModel) TablaClientes.getModel();
            model.setRowCount(0);
            
            for (Cliente cli : clientes){
                Object[] row = {
                    cli.getIdCliente(),
                    cli.getPrimerNombre(),
                    cli.getSegundoNombre(),
                    cli.getPrimerApellido(),
                    cli.getSegundoApellido(),
                    cli.getCelular(),
                    cli.getDireccion(),
                    cli.getCedula()
                };
                model.addRow(row);
            }
        }
    }
    
    private void limpiar() {
TextPrimerNombre.setText("");
TextSegundoNombre.setText("");
TextPrimerApellido.setText("");
TextSegundoApellido.setText("");
TextCelular.setText("");
TextDireccion.setText("");
TextCedula.setText("");
idClienteSeleccionado = null;
btnEliminar.setEnabled(true);
btnGuardar.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextPrimerNombre = new javax.swing.JTextField();
        TextSegundoNombre = new javax.swing.JTextField();
        TextPrimerApellido = new javax.swing.JTextField();
        TextSegundoApellido = new javax.swing.JTextField();
        TextCelular = new javax.swing.JTextField();
        TextDireccion = new javax.swing.JTextField();
        TextCedula = new javax.swing.JTextField();
        TextBuscar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();

        jLabel1.setText("Primer Nombre");

        jLabel2.setText("Segundo Nombre");

        jLabel3.setText("Primer Apellido");

        jLabel4.setText("Segundo Apellido");

        jLabel5.setText("Celular");

        jLabel6.setText("Direccion");

        jLabel7.setText("Cedula");

        TextBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textBuscarKeyTyped(evt);
            }
        });

        jLabel8.setText("Buscar");

        btnLimpiar.setText("Limpiar");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonGuardar(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonEliminar(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonActualizar(evt);
            }
        });

        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id Cliente", "Primer Nombre", "Segundo Nombre", "Primer Apellido", "Segundo Apellido", "Celular", "Direccion", "Cedula"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(TextPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(TextSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(TextPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel5)
                                .addGap(38, 38, 38))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TextCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(18, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(21, 21, 21))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar))
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accionBotonGuardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonGuardar
        // TODO add your handling code here:
        String PrimerNombre = TextPrimerNombre.getText();
        String SegundoNombre = TextSegundoNombre.getText();
        String PrimerApellido = TextPrimerApellido.getText();
        String SegundoApellido = TextSegundoApellido.getText();
        String Celular = TextCelular.getText();
        String Direccion = TextDireccion.getText();
        String Cedula = TextCedula.getText();
        
        if(!PrimerNombre.isEmpty()&& !PrimerApellido.isEmpty()&& !Celular.isEmpty()&& !Direccion.isEmpty()&& !Cedula.isEmpty()){
           try{
               clienteControlador.crearCliente(PrimerNombre, SegundoNombre, PrimerApellido, SegundoApellido, Celular, Direccion, Cedula);
               limpiar();
               cargarDatosTabla();
           }catch(Exception e){
               javax.swing.JOptionPane.showMessageDialog(this, "Error:"+ e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
               
           }
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Llene los campos requeridos.","Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_accionBotonGuardar

    private void accionBotonEliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonEliminar
        // TODO add your handling code here:
        int filaSeleccionada = TablaClientes.getSelectedRow();
        if(filaSeleccionada != -1){
            int idCliente =(int) TablaClientes.getValueAt(filaSeleccionada, 0);
           clienteControlador.eliminarCliente(idCliente);
           cargarDatosTabla();
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "selecciona una fila para eliminar.","Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accionBotonEliminar

    private void accionBotonActualizar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonActualizar
        // TODO add your handling code here:
        String PrimerNombre = TextPrimerNombre.getText();
        String SegundoNombre = TextSegundoNombre.getText();
        String PrimerApellido = TextPrimerApellido.getText();
        String SegundoApellido = TextSegundoApellido.getText();
        String Celular = TextCelular.getText();
        String Direccion = TextDireccion.getText();
        String Cedula = TextCedula.getText();
        
        if(idClienteSeleccionado != null && !PrimerNombre.isEmpty()&& !PrimerApellido.isEmpty()&& !Celular.isEmpty()){
            try{
                clienteControlador.actualizarCliente(idClienteSeleccionado, PrimerNombre, SegundoNombre, PrimerApellido, SegundoApellido, Celular, Direccion, Cedula);
                cargarDatosTabla();
                limpiar();
            }catch(Exception e){
                javax.swing.JOptionPane.showMessageDialog(this, "Error:"+ e.getMessage(),"Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "llene los campos obligatorios :|","Error",javax.swing.JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_accionBotonActualizar

    private void textBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBuscarKeyTyped
        // TODO add your handling code here:
        String TextBusqueda = TextBuscar.getText().trim().toLowerCase();
        List<Cliente> clientes =clienteControlador.obtenerTodosClientes();
        
        DefaultTableModel modelo = (DefaultTableModel) TablaClientes.getModel();
        modelo.setRowCount(0);
        
        if(clientes !=null){
            for (Cliente cli: clientes){
                if(TextBusqueda.isEmpty()||
                        cli.getPrimerNombre().toLowerCase().contains(TextBusqueda)||
                        (cli.getSegundoNombre()!=null && cli.getSegundoNombre().toLowerCase().contains(TextBusqueda))||
                        cli.getPrimerApellido().toLowerCase().contains(TextBusqueda)||
                        (cli.getSegundoApellido()!=null && cli.getSegundoApellido().toLowerCase().contains(TextBusqueda))||
                        cli.getCelular().toLowerCase().contains(TextBusqueda)||
                        cli.getDireccion().toLowerCase().contains(TextBusqueda)||
                        cli.getCedula().toLowerCase().contains(TextBusqueda)){
                    Object[] fila ={
                        cli.getIdCliente(),
                        cli.getPrimerNombre(),
                        cli.getSegundoNombre(),
                        cli.getPrimerApellido(),
                        cli.getSegundoApellido(),
                        cli.getCelular(),
                        cli.getDireccion(),
                        cli.getCedula()
                    };
                    modelo.addRow(fila);
                }
            }
        }
    }//GEN-LAST:event_textBuscarKeyTyped

    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount()== 2){
            int filaSeleccionada = TablaClientes.getSelectedRow();
            
            if (filaSeleccionada != -1){
                
                idClienteSeleccionado = (int) TablaClientes.getValueAt(filaSeleccionada, 0);
                String PrimerNombre = (String) TablaClientes.getValueAt(filaSeleccionada, 1);
                String SegundoNombre = (String) TablaClientes.getValueAt(filaSeleccionada, 2);
                String PrimerApellido = (String) TablaClientes.getValueAt(filaSeleccionada, 3);
                String SegundoApellido = (String) TablaClientes.getValueAt(filaSeleccionada, 4);
                String Celular = (String) TablaClientes.getValueAt(filaSeleccionada, 5);
                String Direccion = (String) TablaClientes.getValueAt(filaSeleccionada, 6);
                String Cedula = (String) TablaClientes.getValueAt(filaSeleccionada, 7);
                
                TextPrimerNombre.setText(PrimerNombre);
                TextSegundoNombre.setText(SegundoNombre);
                TextPrimerApellido.setText(PrimerApellido);
                TextSegundoApellido.setText(SegundoApellido);
                TextCelular.setText(Celular);
                TextDireccion.setText(Direccion);
                TextCedula.setText(Cedula);
                
                btnEliminar.setEnabled(false);
                btnGuardar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tablaClientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaClientes;
    private javax.swing.JTextField TextBuscar;
    private javax.swing.JTextField TextCedula;
    private javax.swing.JTextField TextCelular;
    private javax.swing.JTextField TextDireccion;
    private javax.swing.JTextField TextPrimerApellido;
    private javax.swing.JTextField TextPrimerNombre;
    private javax.swing.JTextField TextSegundoApellido;
    private javax.swing.JTextField TextSegundoNombre;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
